# DNS name of Network Load Balancer
nlb: nlb-oupt-4631dc4e3819202e.elb.eu-west-3.amazonaws.com

# main path to deploy ansible
main_path: "/home/researcher"

name_cluster: "cluster-rese-oupt"

# Routes to the internal network. Added with netplan
workers:
  routes:
    - to: 10.11.0.0/16
      via: 10.11.29.1
    - to: 10.182.32.0/24
      via: 10.11.29.1


metalLb:
  enable: false
  name: ip-pooladdress-local
  poolAddress: 192.168.1.30-192.168.1.50

cert_manager:
  enable: false

aws_lb_controller:
  enable: false
  
ingress_nginx:
  enable: false