apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
 name: tactile5g-local-central-dc
 namespace: actions-runner-system
spec:
 replicas: 3
 template:
   spec:
     repository: andresanaya21/tactile5g-local-central-dc

---

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
 name: tactile5g-local-central-dc-ext-node
 namespace: actions-runner-system
spec:
 replicas: 3
 template:
   spec:
     repository: andresanaya21/tactile5g-local-central-dc
     nodeSelector:
      node: external-node
